/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package enrollmentsystem.gui;

import enrollmentsystem.data.AppQuery;
import enrollmentsystem.data.ComboBoxList;
import enrollmentsystem.records.Role;
import enrollmentsystem.records.Student;
import enrollmentsystem.util.ComboBoxAutoFill;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.sql.Blob;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogRegister extends javax.swing.JDialog implements MouseListener {

    private JTextComponent editor;
    private AppQuery query = new AppQuery();

    public JDialogRegister(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTable();
        comboBoxStudent();
        jComboBoxStudentID.setEditable(true);
        editor = (JTextComponent) jComboBoxStudentID.getEditor().getEditorComponent();
        editor.addKeyListener(new ComboBoxItemKeyListener());
        editor.setDocument(new ComboBoxAutoFill(jComboBoxStudentID));
        comboBoxClassCode();
        jComboBoxClassCode.setEditable(true);
        editor = (JTextComponent) jComboBoxClassCode.getEditor().getEditorComponent();
        editor.addKeyListener(new ComboBoxItemKeyListener());
        editor.setDocument(new ComboBoxAutoFill(jComboBoxClassCode));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPhoto = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldStudentName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxStudentID = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCivilStatus = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldGender = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCourse = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldReligion = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jComboBoxClassCode = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelPhoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPhoto.setText("NO PHOTO");
        jLabelPhoto.setMaximumSize(new java.awt.Dimension(118, 118));
        jLabelPhoto.setMinimumSize(new java.awt.Dimension(118, 118));
        jLabelPhoto.setPreferredSize(new java.awt.Dimension(118, 118));
        jPanel1.add(jLabelPhoto, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 118, 118));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT INFORMATION", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("STUDENT NAME");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel3, java.awt.BorderLayout.NORTH);

        jTextFieldStudentName.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextFieldStudentName.setFocusable(false);
        jTextFieldStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStudentNameActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldStudentName, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 18, 290, 46));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText("STUDENT CODE");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel2, java.awt.BorderLayout.NORTH);

        jComboBoxStudentID.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jComboBoxStudentID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxStudentIDItemStateChanged(evt);
            }
        });
        jComboBoxStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStudentIDActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxStudentID, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 19, 150, 46));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setText("CIVIL STATUS");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel6, java.awt.BorderLayout.NORTH);

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel7.setText("CIVIL STATUS");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel7.add(jLabel7, java.awt.BorderLayout.NORTH);

        jTextFieldCivilStatus.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jTextFieldCivilStatus.setFocusable(false);
        jPanel7.add(jTextFieldCivilStatus, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 72, 120, 46));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("GENDER");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel5.add(jLabel4, java.awt.BorderLayout.NORTH);

        jTextFieldGender.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextFieldGender.setFocusable(false);
        jPanel5.add(jTextFieldGender, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 72, 100, 46));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("COURSE");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel5, java.awt.BorderLayout.NORTH);

        jTextFieldCourse.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        jTextFieldCourse.setFocusable(false);
        jPanel6.add(jTextFieldCourse, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 18, 325, 46));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setText("CIVIL STATUS");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(jLabel8, java.awt.BorderLayout.NORTH);

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel9.setText("RELIGION");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel8.add(jLabel9, java.awt.BorderLayout.NORTH);

        jTextFieldReligion.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        jTextFieldReligion.setFocusable(false);
        jPanel8.add(jTextFieldReligion, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 72, 210, 46));

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel11.setText("ADDRESS");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel11, java.awt.BorderLayout.NORTH);

        jTextFieldAddress.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldAddress.setFocusable(false);
        jPanel9.add(jTextFieldAddress, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 72, 325, 46));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 32, 805, 126));

        jComboBoxClassCode.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jComboBoxClassCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClassCodeActionPerformed(evt);
            }
        });
        jComboBoxClassCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxClassCodeKeyPressed(evt);
            }
        });
        getContentPane().add(jComboBoxClassCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 860, 35));

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, 920, 270));

        jButtonAdd.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jButtonAdd.setText("ADD");
        jButtonAdd.setMargin(new java.awt.Insets(2, 2, 3, 2));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 165, 50, 35));

        jButton3.setText("<html><center>REGISTER<BR>STUDENT</center></html>");
        jButton3.setMaximumSize(new java.awt.Dimension(79, 39));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, 40));

        jButton4.setText("<html><center>PRINT<BR>COR</center></html>");
        jButton4.setMaximumSize(new java.awt.Dimension(79, 39));
        jButton4.setMinimumSize(new java.awt.Dimension(79, 39));
        jButton4.setPreferredSize(new java.awt.Dimension(79, 39));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 80, 40));

        jButton5.setText("<html><center>DROP<BR>SUBJECT</center></html>");
        jButton5.setMaximumSize(new java.awt.Dimension(79, 39));
        jButton5.setMinimumSize(new java.awt.Dimension(79, 39));
        jButton5.setPreferredSize(new java.awt.Dimension(79, 39));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 80, 40));

        jButton6.setText("<html><center>ADD<BR>SUBJECT</center></html>");
        jButton6.setMaximumSize(new java.awt.Dimension(79, 39));
        jButton6.setMinimumSize(new java.awt.Dimension(79, 39));
        jButton6.setPreferredSize(new java.awt.Dimension(79, 39));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, 80, 40));

        setSize(new java.awt.Dimension(956, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStudentNameActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxStudentIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxStudentIDItemStateChanged

    }//GEN-LAST:event_jComboBoxStudentIDItemStateChanged

    private void jComboBoxStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStudentIDActionPerformed
        editor = (JTextComponent) jComboBoxStudentID.getEditor().getEditorComponent();
        if (editor.getText().isBlank()) {
            jButtonAdd.setEnabled(false);
            jLabelPhoto.setIcon(null);
            jLabelPhoto.setText("NO PHOTO");
            jTextFieldStudentName.setText("");
            jTextFieldCourse.setText("");
            jTextFieldGender.setText("");
            jTextFieldCivilStatus.setText("");
            jTextFieldReligion.setText("");
            jTextFieldAddress.setText("");
            jComboBoxClassCode.setEnabled(false);
            comboBoxClassCode();
            jComboBoxClassCode.setEditable(true);
            editor = (JTextComponent) jComboBoxClassCode.getEditor().getEditorComponent();
            editor.addKeyListener(new ComboBoxItemKeyListener());
            editor.setDocument(new ComboBoxAutoFill(jComboBoxClassCode));
            jButtonAdd.setEnabled(false);

        } else {
            jLabelPhoto.setText(null);
            ComboBoxList studentId = (ComboBoxList) jComboBoxStudentID.getSelectedItem();
            displayPicture(Integer.parseInt(studentId.getId()));
            Student s = query.getStudentInformation(Integer.parseInt(studentId.getId()));
            jTextFieldStudentName.setText(s.lastname().toUpperCase() + ", " + s.firstname().toUpperCase() + " " + s.middlename().toUpperCase().substring(0, 1) + ".");
            jTextFieldCourse.setText(s.course().course().toUpperCase());
            jTextFieldGender.setText(s.gender().toUpperCase());
            jTextFieldCivilStatus.setText(s.civilStatus().civilStatus().toUpperCase());
            jTextFieldReligion.setText(s.religion().toUpperCase());
            jTextFieldAddress.setText(s.address().toUpperCase());
            jComboBoxClassCode.setEnabled(true);
            jButtonAdd.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxStudentIDActionPerformed

    private void jComboBoxClassCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClassCodeActionPerformed
        editor = (JTextComponent) jComboBoxClassCode.getEditor().getEditorComponent();
        if (editor.getText().isBlank()) {

        } else {
            ComboBoxList studentId = (ComboBoxList) jComboBoxClassCode.getSelectedItem();
            addClassToStudent(Integer.parseInt(studentId.getId()));

        }
    }//GEN-LAST:event_jComboBoxClassCodeActionPerformed

    private void jComboBoxClassCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxClassCodeKeyPressed

    }//GEN-LAST:event_jComboBoxClassCodeKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<Object> jComboBoxClassCode;
    private javax.swing.JComboBox<Object> jComboBoxStudentID;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPhoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCivilStatus;
    private javax.swing.JTextField jTextFieldCourse;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldReligion;
    private javax.swing.JTextField jTextFieldStudentName;
    // End of variables declaration//GEN-END:variables
     DefaultTableModel tmodel = new DefaultTableModel() {
        public Class
                getColumnClass(int columnIndex) {
            if (columnIndex == 0) {
                return String.class;

            }
            switch (columnIndex) {

                case 1:
                    return String.class;

                case 2:
                    return String.class;

                case 3:
                    return String.class;

                case 4:
                    return String.class;

                case 5:
                    return String.class;

                case 6:
                    return String.class;

                case 7:
                    return String.class;

                case 8:
                    return String.class;

                case 9:
                    return String.class;

                case 10:
                    return String.class;
                default:
                    return String.class;
            }
        }

        //note that the data/cell address is constant
        //no matter where the cell appears onscreen.
        public boolean isCellEditable(int row, int col) {
            if (col < 30) {
                return false;

            } else {
                return true;
            }
        }
    };
    private TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tmodel);
    public static final DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();

    public void mouseClicked(MouseEvent e) {
        if (e.getSource() == jTable1) {
            if (e.getButton() == MouseEvent.BUTTON1) {
                if (e.getClickCount() == 1) {
                    int row = jTable1.getSelectedRow();

                    if (row != -1) {
                        Object studentIdl = jTable1.getValueAt(row, 0);
                        Object courseIdl = jTable1.getValueAt(row, 1);
                        Object accountCodel = jTable1.getValueAt(row, 2);
                        Object studentNamel = jTable1.getValueAt(row, 3);
                        Object lastNamel = jTable1.getValueAt(row, 4);
                        Object firstNamel = jTable1.getValueAt(row, 5);
                        Object middleNamel = jTable1.getValueAt(row, 6);

                    }
                }
            }
        }
    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }

    private void setTable() {
        String[] columnNames = {
            "CLASS ID",
            "CLASS CODE",
            "DESCRIPTION",
            "UNITS",
            "DAY",
            "TIME",
            "ROOM",
            "INSTRUCTOR"
        };

        jTable1.setCellSelectionEnabled(true);
        jTable1 = new JTable(tmodel);
        JTableHeader header = jTable1.getTableHeader();
        header.setPreferredSize(new Dimension(100, 32));
        header.setFont(new Font("Courier New", Font.PLAIN, 14));
//            header.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setRowSorter(sorter);
        jTable1.addMouseListener(this);
        jTable1.setRowHeight(28);
        jTable1.setFont(new Font("Courier New", Font.PLAIN, 14));
        jScrollPane1.setViewportView(jTable1);
        for (int i = 0; i < columnNames.length;) {
            tmodel.addColumn(columnNames[i]);
            i++;
        }

        TableColumn[] column = new TableColumn[100];
        column[0] = jTable1.getColumnModel().getColumn(0);
        column[0].setPreferredWidth(6);

        column[1] = jTable1.getColumnModel().getColumn(1);
        column[1].setPreferredWidth(60);

        column[2] = jTable1.getColumnModel().getColumn(2);
        column[2].setPreferredWidth(260);

        column[3] = jTable1.getColumnModel().getColumn(3);
        column[3].setPreferredWidth(6);

        column[4] = jTable1.getColumnModel().getColumn(4);
        column[4].setPreferredWidth(6);

        column[5] = jTable1.getColumnModel().getColumn(5);
        column[5].setPreferredWidth(80);

        column[6] = jTable1.getColumnModel().getColumn(6);
        column[6].setPreferredWidth(6);

        column[7] = jTable1.getColumnModel().getColumn(7);
        column[7].setPreferredWidth(100);

        TableColumn hidden1 = jTable1.getColumnModel().getColumn(0);
        hidden1.setMinWidth(0);
        hidden1.setPreferredWidth(0);
        hidden1.setMaxWidth(0);
    }

    class ComboBoxItemKeyListener extends KeyAdapter {

        public void keyPressed(KeyEvent evt) {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ComboBoxList studentId = (ComboBoxList) jComboBoxStudentID.getSelectedItem();
                displayPicture(Integer.parseInt(studentId.getId()));
            }
        }
    }

    private void comboBoxStudent() {
        query.comboBoxStudentId();
        jComboBoxStudentID.removeAllItems();
        for (ComboBoxList a : query.getList()) {
            this.jComboBoxStudentID.addItem(a);
        }
    }

    private void displayPicture(Integer id) {
        try {
            Blob blobImage = (Blob) query.selectedStudentPhoto(id);
            ImageIcon icon = new ImageIcon(blobImage.getBytes(1L, (int) blobImage.length()));

            Image image = icon.getImage();

            int IMG_WIDTH = 118;
            int IMG_HEIGHT = 118;
            int type = BufferedImage.TYPE_INT_ARGB;

            BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
            Graphics2D g = resizedImage.createGraphics();
            g.drawImage(image, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
            g.dispose();
            g.setComposite(AlphaComposite.Src);

            g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
                    RenderingHints.VALUE_INTERPOLATION_BILINEAR);
            g.setRenderingHint(RenderingHints.KEY_RENDERING,
                    RenderingHints.VALUE_RENDER_QUALITY);
            g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

            jLabelPhoto.setIcon(new ImageIcon(resizedImage));//image to label

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void comboBoxClassCode() {
        query.comboBoxClassCode();
        jComboBoxClassCode.removeAllItems();
        for (ComboBoxList a : query.getList()) {
            this.jComboBoxClassCode.addItem(a);
        }
    }

    private void selectClassCode() {

    }

    private void addClassToStudent(Integer id) {
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
