/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package enrollmentsystem.gui.dialog.au;

import enrollmentsystem.data.AppQuery;
import enrollmentsystem.records.Room;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogRoomAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogUserAU
     */
    private Room room;
    private enrollmentsystem.gui.JFrameEnrollment mainFrame;

    public JDialogRoomAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Add room");
        jButton1.setText("Save");
        jButton1.setMnemonic('S');

    }

    public JDialogRoomAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal, Room room) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Update room");
        jButton1.setText("Update");
        jTextFieldRoom.setText(room.room());
        jTextFieldLocation.setText(room.location());
        jButton1.setMnemonic('U');
        this.room = room;
        jButton1.setEnabled(false);
    }

    public JDialogRoomAU(enrollmentsystem.gui.JFrameEnrollment parent, Room room, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Delete room");
        jButton1.setText("Delete");
        jTextFieldRoom.setText(room.room());
        jTextFieldLocation.setText(room.location());
        jTextFieldRoom.setFocusable(false);
        jTextFieldLocation.setFocusable(false);
        jButton1.setMnemonic('D');
        this.room = room;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldRoom = new javax.swing.JTextField();
        jTextFieldLocation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ROOM:");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("LOCATION:");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 97, 80));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jTextFieldRoom.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldRoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRoomKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldRoom);

        jTextFieldLocation.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLocationKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldLocation);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 21, 280, 80));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, -1));

        setSize(new java.awt.Dimension(413, 200));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jButton1.getText().equals("Save")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to add " + jTextFieldRoom.getText() + " ?", "Add room confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Room room = new Room(null, jTextFieldRoom.getText(), jTextFieldLocation.getText());
                new AppQuery().addRoom(room);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Update")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to update " + jTextFieldRoom.getText() + " ?", "Add room confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Room room = new Room(this.room.id(), jTextFieldRoom.getText(), jTextFieldLocation.getText());
                new AppQuery().updateRoom(room);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to delete " + jTextFieldRoom.getText() + " ?", "Add room confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Room room = new Room(this.room.id(), jTextFieldRoom.getText(), jTextFieldLocation.getText());
                new AppQuery().deleteRoom(room);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldRoomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRoomKeyReleased
        if (jButton1.getText().equals("Save")) {

        } else {
            isCourseUpdated();
        }


    }//GEN-LAST:event_jTextFieldRoomKeyReleased

    private void jTextFieldLocationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocationKeyReleased
        if (jButton1.getText().equals("Save")) {

        } else {
            isCourseUpdated();
        }
    }//GEN-LAST:event_jTextFieldLocationKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldRoom;
    // End of variables declaration//GEN-END:variables
  private void isCourseUpdated() {
        Room c = new Room(this.room.id(), jTextFieldRoom.getText(), jTextFieldLocation.getText());
        if ((c.room().length() == 0) || (c.location().length() == 0)) {
            jButton1.setEnabled(false);
            return;
        }
        if (this.room.equals(c)) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }

}
