/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package enrollmentsystem.gui.dialog.au;

import enrollmentsystem.data.AppQuery;
import enrollmentsystem.records.Course;
import enrollmentsystem.records.SchoolYear;
import enrollmentsystem.records.Semester;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogSemesterAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogUserAU
     */
    private Semester semester;
    private enrollmentsystem.gui.JFrameEnrollment mainFrame;
    private AppQuery query = new AppQuery();

    public JDialogSemesterAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Add semester");
        jButton1.setText("Save");
        jButton1.setMnemonic('S');

    }

    public JDialogSemesterAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal, Semester semester) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Update semester");
        jButton1.setText("Update");
        jTextFieldSemester.setText(String.valueOf(semester.semester()));
        jButton1.setMnemonic('U');
        this.semester = semester;
        jButton1.setEnabled(false);
    }

    public JDialogSemesterAU(enrollmentsystem.gui.JFrameEnrollment parent, Semester semester, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Delete semester");
        jButton1.setText("Delete");
        jTextFieldSemester.setText(String.valueOf(semester.semester()));
        jTextFieldSemester.setFocusable(false);
        jButton1.setMnemonic('D');
        this.semester = semester;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldSemester = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SEMESTER:");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 97, 40));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jTextFieldSemester.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldSemester.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSemesterKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldSemester);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 21, 280, 40));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, -1));

        setSize(new java.awt.Dimension(413, 163));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jButton1.getText().equals("Save")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to add " + jTextFieldSemester.getText() + " ?", "Add time confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Semester sy = new Semester(0, jTextFieldSemester.getText());
                new AppQuery().addSemester(sy);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Update")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to update " + jTextFieldSemester.getText() + " ?", "Add time confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Semester sy = new Semester(this.semester.id(), jTextFieldSemester.getText());
                new AppQuery().updateSemester(sy);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to delete " + jTextFieldSemester.getText() + " ?", "Add time confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Semester sy = new Semester(this.semester.id(), jTextFieldSemester.getText());
                new AppQuery().deleteSemester(sy);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSemesterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSemesterKeyReleased
        isSemesterUpdated();
    }//GEN-LAST:event_jTextFieldSemesterKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldSemester;
    // End of variables declaration//GEN-END:variables

    private void isSemesterUpdated() {
        Semester c = new Semester(this.semester.id(), jTextFieldSemester.getText());
        if ((c.semester().length() == 0) || (c.semester().length() == 0)) {
            jButton1.setEnabled(false);
            return;
        }
        if (this.semester.equals(c)) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }
    }
}
