/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package enrollmentsystem.gui.dialog.au;

import enrollmentsystem.data.AppQuery;
import enrollmentsystem.records.Course;
import enrollmentsystem.records.Role;
import javax.swing.JOptionPane;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogRoleAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogUserAU
     */
    private Role role;
    private enrollmentsystem.gui.JFrameEnrollment mainFrame;

    public JDialogRoleAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Add Role");
        jButton1.setText("Save");
        jButton1.setMnemonic('S');

    }

    public JDialogRoleAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal, Role role) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Update Role");
        jButton1.setText("Update");
        jTextFieldRole.setText(role.role());
        jButton1.setMnemonic('U');
        this.role = role;
        jCheckBoxMUser.setSelected(role.mUser());
        jCheckBoxMRegister.setSelected(role.mRegister());
        jCheckBoxMClassOffer.setSelected(role.mSubjectOffer());
    }

    public JDialogRoleAU(enrollmentsystem.gui.JFrameEnrollment parent, Role role, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainFrame = parent;
        setTitle("Delete Role");
        jButton1.setText("Delete");
        jTextFieldRole.setText(role.role());
        jTextFieldRole.setFocusable(false);
        jButton1.setMnemonic('D');
        this.role = role;
        jCheckBoxMUser.setSelected(role.mUser());
        jCheckBoxMRegister.setSelected(role.mRegister());
        jCheckBoxMClassOffer.setSelected(role.mSubjectOffer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldRole = new javax.swing.JTextField();
        jCheckBoxMUser = new javax.swing.JCheckBox();
        jCheckBoxMRegister = new javax.swing.JCheckBox();
        jCheckBoxMClassOffer = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Role:");
        jPanel1.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 97, 80));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jTextFieldRole.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldRole);

        jCheckBoxMUser.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jCheckBoxMUser.setText("MANAGE USER");
        jCheckBoxMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMUserActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBoxMUser);

        jCheckBoxMRegister.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jCheckBoxMRegister.setText("MANAGE REGISTRATION");
        jPanel2.add(jCheckBoxMRegister);

        jCheckBoxMClassOffer.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jCheckBoxMClassOffer.setText("MANAGE CLASS OFFER");
        jPanel2.add(jCheckBoxMClassOffer);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 21, 280, 160));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 190, 130, -1));

        setSize(new java.awt.Dimension(413, 282));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jButton1.getText().equals("Save")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to add " + jTextFieldRole.getText() + " ?", "Add role confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Role r = new Role(null, jTextFieldRole.getText(), jCheckBoxMUser.isSelected(), jCheckBoxMRegister.isSelected(), jCheckBoxMClassOffer.isSelected());
                new AppQuery().addRole(r);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Update")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to update " + jTextFieldRole.getText() + " ?", "Add role confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Role r = new Role(null, jTextFieldRole.getText(), jCheckBoxMUser.isSelected(), jCheckBoxMRegister.isSelected(), jCheckBoxMClassOffer.isSelected());
                new AppQuery().updateRole(r);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to delete " + jTextFieldRole.getText() + " ?", "Add role confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                Role r = new Role(null, jTextFieldRole.getText(), jCheckBoxMUser.isSelected(), jCheckBoxMRegister.isSelected(), jCheckBoxMClassOffer.isSelected());
                new AppQuery().deleteRole(r);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBoxMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxMClassOffer;
    private javax.swing.JCheckBox jCheckBoxMRegister;
    private javax.swing.JCheckBox jCheckBoxMUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldRole;
    // End of variables declaration//GEN-END:variables

}
