/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package enrollmentsystem.gui.dialog.au;

import enrollmentsystem.data.AppQuery;
import enrollmentsystem.data.ComboBoxList;
import enrollmentsystem.gui.JFrameEnrollment;
import enrollmentsystem.records.Role;
import enrollmentsystem.records.User;
import enrollmentsystem.util.ComboBoxAutoFill;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Java Programming with Aldrin
 */
public class JDialogUserAU extends javax.swing.JDialog {

    /**
     * Creates new form JDialogUserAU
     */
    private AppQuery query = new AppQuery();
    private JTextComponent editor;
    private JFrameEnrollment mainFrame;
    private User user;

    public JDialogUserAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Add student");
        comboBoxRole();
        jComboBoxRole.setEditable(true);
        editor = (JTextComponent) jComboBoxRole.getEditor().getEditorComponent();
        editor.setDocument(new ComboBoxAutoFill(jComboBoxRole));
        jButton1.setText("Save");
        jButton1.setMnemonic('S');
    }

    public JDialogUserAU(enrollmentsystem.gui.JFrameEnrollment parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();
        setTitle("Update student");
        comboBoxRole();
//        jComboBoxRole.setEditable(true);
//        editor = (JTextComponent) jComboBoxRole.getEditor().getEditorComponent();
//        editor.setDocument(new ComboBoxAutoFill(jComboBoxRole));
        jButton1.setText("Update");
        jButton1.setMnemonic('U');
        this.user = user;
        jTextFieldFirstname.setText(user.firstname());
        jTextFieldMiddlename.setText(user.middlename());
        jTextFieldLastname.setText(user.lastname());
        jTextFieldUsername.setText(user.username());
        jTextFieldPassword.setText(user.password());
        for (ComboBoxList a : this.query.getList()) {
            a.setSelectedId(query.getList(), String.valueOf(user.role().id()), jComboBoxRole);
        }
    }

    public JDialogUserAU(enrollmentsystem.gui.JFrameEnrollment parent, User user, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Delete student");
        comboBoxRole();
        jComboBoxRole.setEditable(true);
        editor = (JTextComponent) jComboBoxRole.getEditor().getEditorComponent();
        editor.setDocument(new ComboBoxAutoFill(jComboBoxRole));
        jButton1.setText("Delete");
        jButton1.setMnemonic('D');
        this.user = user;
        jTextFieldFirstname.setText(user.firstname());
        jTextFieldMiddlename.setText(user.middlename());
        jTextFieldLastname.setText(user.lastname());
        jTextFieldUsername.setText(user.username());
        jTextFieldPassword.setText(user.password());
        System.out.println("roleId:"+user.role().id());
        for (ComboBoxList a : this.query.getList()) {
            a.setSelectedId(query.getList(), String.valueOf(user.role().id()), jComboBoxRole);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldMiddlename = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldPassword = new javax.swing.JTextField();
        jComboBoxRole = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("FIRST NAME:");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("MIDDLE NAME:");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("LAST NAME:");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("USERNAME:");
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("PASSWORD:");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("ROLE:");
        jPanel1.add(jLabel6);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 97, 235));

        jPanel2.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        jTextFieldFirstname.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldFirstname);

        jTextFieldMiddlename.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldMiddlename);

        jTextFieldLastname.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldLastname);

        jTextFieldUsername.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldUsername);

        jTextFieldPassword.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jTextFieldPassword);

        jComboBoxRole.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jPanel2.add(jComboBoxRole);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 21, 280, 235));

        jButton1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setPreferredSize(new java.awt.Dimension(72, 36));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 268, 140, -1));

        setSize(new java.awt.Dimension(413, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jButton1.getText().equals("Save")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to add " + jTextFieldFirstname.getText() + " " + jTextFieldLastname.getText() + " ?", "Add course confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                ComboBoxList roleId = (ComboBoxList) this.jComboBoxRole.getSelectedItem();
                Role role = new Role(Integer.parseInt(roleId.getId()), roleId.getName(), false, false, false);
                User user = new User(0, jTextFieldFirstname.getText(), jTextFieldMiddlename.getText(), jTextFieldLastname.getText(), jTextFieldUsername.getText(), jTextFieldPassword.getText(), role);
                new AppQuery().addUser(user);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Update")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to update " + jTextFieldFirstname.getText() + " " + jTextFieldLastname.getText() + " ?", "Add course confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                ComboBoxList roleId = (ComboBoxList) this.jComboBoxRole.getSelectedItem();
                Role role = new Role(Integer.parseInt(roleId.getId()), roleId.getName(), false, false, false);
                User user = new User(this.user.id(), jTextFieldFirstname.getText(), jTextFieldMiddlename.getText(), jTextFieldLastname.getText(), jTextFieldUsername.getText(), jTextFieldPassword.getText(), role);
                new AppQuery().updateUser(user);
                this.dispose();
            }
        } else if (jButton1.getText().equals("Delete")) {
            int response = JOptionPane.showConfirmDialog(mainFrame, "Are you sure to update " + jTextFieldFirstname.getText() + " " + jTextFieldLastname.getText() + " ?", "Add course confirmation", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.YES_OPTION) {
                new AppQuery().deleteUser(this.user);
                this.dispose();
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<Object> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    private javax.swing.JTextField jTextFieldMiddlename;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables

    private void comboBoxRole() {
        this.jComboBoxRole.removeAllItems();
        query.comboBoxRole();
        for (ComboBoxList a : query.getList()) {
            this.jComboBoxRole.addItem(a);
        }
    }

}
